# Chapter 6

## Invisible text

I have a Quarto extension [Invisible text extension](https://github.com/david-hodge/invis) to make hiding text easy. Mostly for us in gapped notes, or perhaps handouts.

It implemented by simply setting text to fully transparent (and not selectable). Screenreaders **will** be able to see it, and they will also get informative notifications about the visibly hidden text. In LaTeX/PDF it is rendered as white text.

Just install it as any other extension via

```
quarto add david-hodge/invis
```

and then you can use it via usage of the following shortcodes.

### Simple hiding

`{{{< invis start >}}}`
: This starts invisibility

`{{{< invis end >}}}`
: This ends invisibility

By default these are designed to hide a single block/element on a page. It can hide a single equation, a single word, a single line or text, etc.. *However* it cannot hide multiple paragraphs or more complex elements.

### Hiding larger elements

To hide more complex elements, use the `block` extra paramater.

`{{{< invis start block >}}}`
: This starts invisibility for a large element

`{{{< invis end block >}}}`
: This ends invisibility for a large element

### Examples

This first sentence is fully visible.

{{< invis start >}}
This second sentence is fully visible.
{{< invis end >}}

This third sentence is fully visible.

:::{.callout-warning}

I don't imagine you would wish, but should you wish to hide some fundamental Quarto object like a code block and the resulting output you are recommended to use the built-in features like setting `echo: false` on the code block.

:::

You can use this `invis` extension to hide large blocks of content in the HTML, but for such elements they will likely appear in the PDF, since all we are doing is setting standard text as white, and code and plots are not standard text.

{{< invis start block >}}

```{r}
#| fig-alt: "Cars plot"
#| label: fig-cars-plot
#| fig-cap: "This is the caption"
plot(cars)
```

{{< invis end block >}}

The code and output plot above are fully hidden in the HTML. Likely fully visible in the PDF.